name: json-rpc
version: 1.1.2
synopsis: Fully-featured JSON-RPC 2.0 library
description: Please see the README on GitHub at <https://github.com/jprupp/json-rpc#readme>
category: Network
author: JP Rupp
maintainer: jprupp@protonmail.ch
license: MIT
license-file: LICENSE
github: jprupp/json-rpc.git
extra-source-files:
- README.md
- CHANGELOG.md
dependencies:
- base >=4.6 && <5
- aeson
- attoparsec-aeson
- bytestring
- conduit
- conduit-extra
- monad-logger
- mtl
- stm-conduit
- text
- time
- unliftio
- unordered-containers
- vector
- QuickCheck
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Network.JSONRPC
  dependencies:
  - attoparsec
  - deepseq
  - hashable
tests:
  test-json-rpc:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-rpc
    - hspec
executables:
  concurrent-client:
    main: examples/concurrent-client.hs
    dependencies:
    - json-rpc
  concurrent-server:
    main: examples/concurrent-server.hs
    dependencies:
    - json-rpc
  time-client:
    main: examples/time-client.hs
    dependencies:
    - json-rpc
  time-server:
    main: examples/time-server.hs
    dependencies:
    - json-rpc
